import streamlit as st
import pandas as pd
import plotly.express as px
import os
from openai import OpenAI

# Page Config
st.set_page_config(page_title="Shadow OS Dashboard", layout="wide", page_icon="📊")

# Setup Groq API (Llama 3.1)
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "your_api_key_here") # Set this in your terminal!
client = OpenAI(api_key=GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")

st.title("📊 Shadow OS Product Strategy Dashboard")
st.markdown("AI-powered analytics and prescriptive strategy powered by **Apache Spark** and **Llama 3.1**.")

# 1. Load Data (In a real scenario, you'd pull this CSV from the HDFS output directory)
@st.cache_data
def load_data():
    # Attempt to load the file generated by the Scala backend
    try:
        df = pd.read_csv("shadow_os_final_report.csv")
    except FileNotFoundError:
        # Fallback dummy data if CSV isn't found just so UI renders
        st.warning("Spark output CSV not found. Loading sample metrics.")
        data = {
            "Category": ["TOP_LEADER"]*10 + ["BOTTOM_RISK"]*5,
            "rank": list(range(1, 11)) + list(range(1, 6)),
            "asin": [f"B00{i}ABC" for i in range(15)],
            "ALS_Predicted_Rating": [4.5 + (i*0.05) for i in range(10)] + [2.0 + (i*0.1) for i in range(5)],
            "Hybrid_Success_Score": [3.5 + (i*0.05) for i in range(10)] + [1.5 + (i*0.1) for i in range(5)]
        }
        df = pd.DataFrame(data)
    return df

df = load_data()
top_10 = df[df['Category'] == 'TOP_LEADER'].sort_values('Hybrid_Success_Score', ascending=False)
bottom_5 = df[df['Category'] == 'BOTTOM_RISK'].sort_values('Hybrid_Success_Score', ascending=True)

# 2. Render Tables
col1, col2 = st.columns(2)
with col1:
    st.subheader("🏆 Top 10 Strategic Leaders")
    st.dataframe(top_10[['rank', 'asin', 'ALS_Predicted_Rating', 'Hybrid_Success_Score']], hide_index=True)

with col2:
    st.subheader("⚠️ Bottom 5 Performance Risks")
    st.dataframe(bottom_5[['rank', 'asin', 'ALS_Predicted_Rating', 'Hybrid_Success_Score']], hide_index=True)

# 3. Render Plotly Chart
st.subheader("📈 Top Product Performance")
fig = px.bar(
    top_10, x='asin', y='Hybrid_Success_Score', 
    color='Hybrid_Success_Score', color_continuous_scale='Blues',
    title="Top Products Ranked by Hybrid Score"
)
st.plotly_chart(fig, use_container_width=True)

# 4. Agentic AI Strategy Generation
st.markdown("---")
st.subheader("🤖 Llama 3.1 Prescriptive Strategy")

if st.button("Generate Strategy Directive"):
    with st.spinner("Consulting Agentic LLM..."):
        top_asins = top_10['asin'].tolist()
        bottom_asins = bottom_5['asin'].tolist()
        
        prompt = f"""
        You are Shadow OS, an elite business strategist. 
        Based on our Spark Big Data pipeline, the Top 10 highest-performing product IDs (ASINs) are: {top_asins}.
        The Bottom 5 highest-risk product IDs (ASINs) are: {bottom_asins}.
        
        Provide a concise, 3-point business strategy on how to handle marketing for the Top 10, and liquidation/damage control for the Bottom 5.
        """
        
        try:
            response = client.chat.completions.create(
                model="llama-3.1-8b-instant",
                messages=[{"role": "system", "content": prompt}],
                temperature=0.3
            )
            st.success("Strategy Generated:")
            st.write(response.choices[0].message.content)
        except Exception as e:
            st.error(f"Failed to connect to Groq API. Check your API key. Error: {e}")